### ISSUE TITLE
Download full chat history

### ISSUE THREAD

**Issue by TobitRE** [pencil/rechat#13]
Hi Nils,

my question is the title :)
Is it possible to download the full chat history in one file?

thanks for your help,

best regards

Tobit

**Comment by pencil** [comment]
There used to be a way to download the chat but I disabled it because some users expressed privacy concerns.

**Comment by pencil** [comment]
Btw. you can find some chat logs here: http://overrustlelogs.net/

I'm in no way affiliated with the site though and I don't know how accurate or complete these logs are.
