### ISSUE TITLE
Messages are not fetched if recorded stream starts with a mature content warning

### ISSUE THREAD

**Issue by avnestico** [pencil/rechat#14]
When playing back a recorded stream which starts with a mature content warning, messages are not fetched. After refreshing the page, the mature content warning is not shown again and messages are fetched like normal.

Tested with http://www.twitch.tv/taerknet/b/663146074?t=1h13m20s (video recorded on 2015-05-26)

**Comment by pencil** [comment]
Thank you for the report. I'm pretty sure I fixed this in 41cf5b7 but will have to do so more testing before releasing a new version.

**Comment by pencil** [comment]
Should be fixed in `0.11.0`
