### ISSUE TITLE
Emote Inserting Error

### ISSUE THREAD

**Issue by goldbattle** [pencil/rechat#22]
![image](https://cloud.githubusercontent.com/assets/2222562/8921508/685a75a8-34a4-11e5-88f1-a20ecc2dbef1.png)

![image](https://cloud.githubusercontent.com/assets/2222562/8921493/49263af0-34a4-11e5-9787-37f84f317aba.png)

![image](https://cloud.githubusercontent.com/assets/2222562/8921497/58f79172-34a4-11e5-889d-1a7c743ab137.png)

It seems to be trying to insert a ![image](http://static-cdn.jtvnw.net/emoticons/v1/44963/2.0) image but seems to be sticking it into the middle of the message. I have seen this a couple times.

**Comment by pencil** [comment]
Thanks for the report. I did some changes to the function that does all the emote and link magic. If you could test the `rewrite-emote-magic` branch, that would be great.

**Comment by goldbattle** [comment]
Yep, seems to be fixed.
![image](https://cloud.githubusercontent.com/assets/2222562/8923710/7adfbef4-34c2-11e5-8032-e0c91602ab2b.png)
