### ISSUE TITLE
Space in Display Name

### ISSUE THREAD

**Issue by Aaron128l** [pencil/rechat#23]
Currently if there is a space in the display name it will show a \s. I'm thinking that is a bug. 
http://puu.sh/jn1o0/e9a1dc507f.png
I also have no idea how the user has a space at the end of his name but....
https://api.twitch.tv/kraken/users/tuff_elite
He does.
Keep up the good work.

**Comment by goldbattle** [comment]
Not sure how that is possible, someone must have missed the trimming code on twitches side.
Very interesting.
