### ISSUE TITLE
Comments don't auto scroll

### ISSUE THREAD

**Issue by godBrother** [pencil/rechat#29]
Comments dont scroll and I have to do it manually

EDIT: Problem seems to occur just by merely scrolling up 1 single time no matter how far you do it, reloading the page is a temporary fix

Windows 10 64bit
Chrome

**Comment by pencil** [comment]
There is now a button saying "More messages below" once you start manually scrolling. Does clicking it fix the problem you are experiencing?

**Comment by godBrother** [comment]
Yes thank you very much man!
